### ISSUE TITLE
[WIP] Roadmap for v1

### ISSUE THREAD

**Issue by yagipy** [yagipy/althea#6]
List of features/changes we want to finish before releasing an official v1 version:

### Syntax
- [x] Support if/else
- [ ] Support for
- [x] Support let
- [ ] Continue processing after match, if, etc.

## Memory management
- [ ] Support Garbage Collection
